### ISSUE TITLE
MSDEPLOY fails for all 3 apps -  azure-cosmosdb-live-data-migrator 

### ISSUE THREAD

**Issue by scleaver** [Azure-Samples/azure-cosmosdb-live-data-migrator#56] opened 2022-10-19 17:16 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Create the registrations and use the "deploy to Azure" button. Tried several times to redeploy without success.

### Any log messages given by the failure
>
{
    "status": "failed",
    "error": {
        "code": "Failed",
        "message": "Failed to download package.\r\nARM-MSDeploy Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&gt; System.Net.WebException: The remote server returned an error: (409) Conflict.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__25.MoveNext()\r\n---&gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (409) Conflict.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&lt;---\r\n'"
    }
}

### Expected/desired behavior
>
Should deploy successfully

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Azure App Service

### Versions
>
Nothing else to add - just followed the instructions.

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dkaubar** [comment] 2022-11-08 14:19
I can see that this happens because storage type for those 3 packages was changed to private. so we can no longer access them.
I found guide/script in one of the active PRs for creating release packages locally (Readme.md): https://github.com/Azure-Samples/azure-cosmosdb-live-data-migrator/pull/42/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 

creating packages locally and hosting them in own SA container fixed the deployment issue.
I still however have issue saying that I'm not authorized to access the site. maybe that's just my misconfiguration, but seeing that this solution in inactive for over a year and various bugs, active PRs don't give much confidence to continue trying to use it

**Comment by henry-chris** [comment] 2022-11-15 21:02
@dkaubar Did you figure this out?  I am having the exact same issue with MSDeploy.

**Comment by dkaubar** [comment] 2022-11-17 09:59
@henry-chris , to deploy the app successfully, you'll need
1. create storage account or any other publicly available storage
2. follow the steps from [this active PR](https://github.com/Azure-Samples/azure-cosmosdb-live-data-migrator/pull/42/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) to create release packages locally
3. upload packages (.zip) to your online storage (must be publicly available)
4. while deploying ARM template set the parameters of urls (3) for app and web job packages to point to your storage

then your deployment should succeed

**Comment by aarvid17** [comment] 2023-01-26 16:29
Have similar issues as you @dkaubar regarding login. "You do not have permission to view this directory or page." Did you get it to work?

**Comment by Marko-TRG** [comment] 2023-01-30 10:31
Same for me, successful deploy but then "You do not have permission to view this directory or page." on the -ui site.

**Comment by Marko-TRG** [comment] 2023-01-30 11:45
Ok, figured it out. My Migration.UI.WebApp.zip file contains a folder within, and the files within that. So, in the UI web app Configuration, Path mapping setting, one needs to add that to the path:

![image](https://user-images.githubusercontent.com/65399316/215468013-bf17cc32-dcb3-4790-9b8d-11975c1ae6db.png)

**Comment by Marko-TRG** [comment] 2023-01-30 14:11
I'm now getting a 500 in the monitor log stream, not sure if this is also path related

<div id="content"> 
<div class="content-container"> 
<h3>HTTP Error 500.50 - URL Rewrite Module Error.</h3> 
<h4>The condition's expression &quot;&#x7b;EnvVarProvider:APPINSIGHTS_JAVASCRIPT_ENABLED&#x7d;&quot; is not valid.</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div>

**Comment by Marko-TRG** [comment] 2023-02-01 09:52
> Have similar issues as you @dkaubar regarding login. "You do not have permission to view this directory or page." Did you get it to work?

This is to do with the file path within the Zip. It must not contain the main folder i.e. Migration.UI.WebApp, Migration.Executor.WebJob and Migration.Monitor.WebJob.
Take note path mapping for the App Services: 'site\wwwroot' for UI, then 'site\wwwroot\App_Data\jobs\continous\Migration-Executor-Job' and 'site\wwwroot\App_Data\jobs\continous\Migration-Monitor-Job'

**Comment by shoshii** [comment] 2023-02-09 00:49
Based on the PR below, I fixed the problems and uploaded the packages to my public storage account.
I think you can build and let the tool work following the repo.
https://github.com/shoshii/azure-cosmosdb-live-data-migrator

I contacted the maintainer and hope the PR will be merged soon..
PR:
https://github.com/Azure-Samples/azure-cosmosdb-live-data-migrator/pull/42

![image](https://user-images.githubusercontent.com/9260450/217685373-3ac47cab-c9a7-4d49-bcfc-4eab8c7e9ee6.png)

**Comment by PaulCardus** [comment] 2023-02-16 17:11
@shoshii what do i need to deploy your version? do i need to run the powershell scripts or can i just take your code and zip then deploy the app?

**Comment by shoshii** [comment] 2023-02-17 00:02
@PaulCardus
You don't need to build the packages yourself. I have already uploaded them at the links below. Please follow the steps in the README to use the packages.

README:
https://github.com/shoshii/azure-cosmosdb-live-data-migrator

zip packages:
https://shoshiicosmosmigration.blob.core.windows.net/migration-tool/Migration.UI.WebApp.zip
https://shoshiicosmosmigration.blob.core.windows.net/migration-tool/Migration.Executor.WebJob.zip
https://shoshiicosmosmigration.blob.core.windows.net/migration-tool/Migration.Monitor.WebJob.zip

Of course you can build the packages with `build.ps1` at the repo's root dir level!

**Comment by PaulCardus** [comment] 2023-02-17 10:13
i get this after deploying your template and files.
HTTP Error 500.30 - ANCM In-Process Start Failure

**Comment by shoshii** [comment] 2023-02-17 10:44
@PaulCardus I would recommend that you locate the UI's Configuration > Stack settings  and set Stack and .NET version like below. Then please try to restart the UI service. It worked for me.
![image](https://user-images.githubusercontent.com/9260450/219622522-9c3bcc1c-7109-4e74-a869-c4c1298221f3.png)

**Comment by PaulCardus** [comment] 2023-02-17 15:01
That all worked, thank you so much for your assistance.

**Closed as not planned** 2023-02-21 16:31 UTC
